rootDirectory: '/home/wilqor/workspaces/Lucene/'
indexDirectories:
  KEYWORD_ANALYZER_EXAMPLE: 'keyword_analyzer'
  FACETING_EXAMPLE: 'faceting'
  WHITESPACE_ANALYZER_EXAMPLE: 'whitespace_analyzer'
  STANDARD_ANALYZER_EXAMPLE: 'standard_analyzer'
  LOWER_CASE_TOKEN_FILTER_EXAMPLE: 'lower_case_token_filter'
  STOP_WORDS_TOKEN_FILTER_EXAMPLE: 'stop_words_token_filter'

