rootDirectory: '/home/zbyszko/workspace/lucene/'
indexDirectories:
  KEYWORD_TOKENIZER_EXAMPLE: 'keyword_tokenizer'
  FACETING_EXAMPLE: 'faceting'
  WHITESPACE_TOKENIZER_EXAMPLE: 'whitespace_tokenizer'
  STANDARD_TOKENIZER_EXAMPLE: 'standard_tokenizer'
  LOWER_CASE_TOKEN_FILTER_EXAMPLE: 'lower_case_token_filter'
  STOP_WORDS_TOKEN_FILTER_EXAMPLE: 'stop_words_token_filter'
  SYNONYM_TOKEN_FILTER_EXAMPLE: 'synonym_token_filter'
  HTML_CHAR_STRIP_FILTER_EXAMPLE: 'html_char_strip_filter'
  WIKIPEDIA_SEARCH: 'wikipedia'

